version: '2'
services:
  postgres:
    container_name: mydb
    image: postgres:12.0-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=spring_project
      - POSTGRES_PASSWORD=admin